language: php

php:
  - 5.5

branches:
  only:
    - master

before_script:
  - sudo apt-get update 
  - sudo apt-get install -y --force-yes libcurl4-openssl-dev php5-curl php5-sqlite php5-intl

  # the client
  - cd client
  - nohup php -S localhost:8000 -t web/ > /dev/null 2>&1 &

  - composer self-update
  - travis_retry composer install --dev --prefer-dist
  # make sure the sqlite dir is readable
  - chmod 777 -R data

script:
    - ./vendor/bin/behat --verbose
